name: Release

on:
  workflow_dispatch:
  push:

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  FORCE_COLOR: 1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITEA_NPM_REGISTRY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
          registry-url: https://gitea.midpathsoftware.com/api/packages/gnpaone/npm
          always-auth: true

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Set registry settings
        run: |
          cat << EOF > "$RUNNER_TEMP/.npmrc"
            //gitea.midpathsoftware.com/api/packages/gnpaone/npm/:_authToken=${NODE_AUTH_TOKEN}
            registry=https://gitea.midpathsoftware.com/api/packages/gnpaone/npm/
            @rrweb:registry=https://gitea.midpathsoftware.com/api/packages/gnpaone/npm/
            @*:registry=https://gitea.midpathsoftware.com/api/packages/gnpaone/npm/
            always-auth=true
          EOF

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn run release
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
