name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
          registry-url: https://gitea.midpathsoftware.com/api/packages/gnpaone/npm
          always-auth: true
          scope: '@rrweb'
        env:
           NODE_AUTH_TOKEN: ${{ secrets.GITEA_NPM_REGISTRY }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Manual Login to NPM Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITEA_NPM_REGISTRY }}
        run: |
          echo -e "${NODE_AUTH_TOKEN}\n\n\n" | npm login --registry=https://gitea.midpathsoftware.com/api/packages/gnpaone/npm


      - name: Set registry settings
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITEA_NPM_REGISTRY }}
        run: |
          echo "registry=https://gitea.midpathsoftware.com/api/packages/gnpaone/npm" > ~/.npmrc
          echo "//gitea.midpathsoftware.com/api/packages/gnpaone/npm/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
          echo '@rrweb:registry=https://gitea.midpathsoftware.com/api/packages/gnpaone/npm/' >> ~/.npmrc

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn run release
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
